services:
  adminer-bigquery-test:
    build:
      context: ../../
      dockerfile: devtools/web/Dockerfile
    container_name: adminer-bigquery-test
    ports:
      - "8080:80"
    volumes:
      # Google Credentials をホストからマウント
      #- /var/tmp/adminer-test-owner.json:/etc/google_credentials.json:ro
      - /var/tmp/adminer-test-owner.json:/etc/google_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/google_credentials.json
      - GOOGLE_CLOUD_PROJECT=adminer-test-472623
      # OAuth2認証設定（テスト用）
      - GOOGLE_OAUTH2_ENABLE=false
      - GOOGLE_OAUTH2_CLIENT_ID=your-oauth2-client-id
      - GOOGLE_OAUTH2_CLIENT_SECRET=your-oauth2-client-secret
      - GOOGLE_OAUTH2_REDIRECT_URL=http://localhost:8080/?oauth2=callback
      - GOOGLE_OAUTH2_COOKIE_DOMAIN=localhost
      - GOOGLE_OAUTH2_COOKIE_NAME=oauth2_token
      - GOOGLE_OAUTH2_COOKIE_EXPIRE=3600
      - GOOGLE_OAUTH2_COOKIE_SECRET=your-cookie-secret-key
    networks:
      - adminer_net
    restart: unless-stopped

networks:
  adminer_net:
    external: true
