services:
  adminer-bigquery-test:
    build:
      context: ../../
      dockerfile: container/web/Dockerfile
    container_name: adminer-bigquery-test
    ports:
      - "8080:80"
    volumes:
      # Google Credentials をホストからマウント
      - /home/hammer/google_credential.json:/etc/google_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/google_credentials.json
      - BIGQUERY_PROJECT_ID=nyle-carmo-analysis
    networks:
      - adminer-net
    restart: unless-stopped

networks:
  adminer-net:
    external: true
