services:
  adminer-bigquery-test:
    build:
      context: ../../
      dockerfile: container/web/Dockerfile
    container_name: adminer-bigquery-test
    ports:
      - "8080:80"
    volumes:
      # Google Credentials をホストからマウント
      - /home/hammer/adminer-test-owner.json:/etc/google_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/google_credentials.json
      - BIGQUERY_PROJECT_ID=adminer-test-472623
    networks:
      - adminer_net
    restart: unless-stopped

networks:
  adminer_net:
    external: true
