services:

  dev:
    image: dev-${COMPOSE_PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.claude.json:/home/ubuntu/.claude.json
      - ~/.serena:/home/ubuntu/.serena
      - ~/.docker:/home/ubuntu/.docker
      - ~/.aws:/home/ubuntu/.aws
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ~/.git-credentials:/home/ubuntu/.git-credentials
      - ~/adminer-test-owner.json:/etc/google_credentials.json:ro
      - work:/home/ubuntu/work
    env_file: ../.env
    user: "${U_ID}:${G_ID}"
    group_add: ["${DOCKER_GID}"]
    command: ["${GIT_USER}", "${GIT_REPO}", "tail", "-f", "/dev/null"]
    networks:
      - net
volumes:
  work:
    driver: local

networks:
  net:
